language: node_js
node_js:
  - 'lts/*'
sudo: required
services:
  - docker
jobs:
  include:
    -
      stage: test
      install: true
      script:
        - 'echo "mocha"'
    -
      stage: build
      install: true
      script:
        - 'echo "building arm"'
        - 'docker run --rm --privileged multiarch/qemu-user-static:register --reset'
        - 'docker build -f Dockerfile.amd64 -t tkurki/signalk-server:linux-amd64-"$BRANCH" .'
    -
      stage: build
      install: true
      script:
        - 'echo "building arm"'
        - 'docker run --rm --privileged multiarch/qemu-user-static:register --reset'
        - 'docker build -f Dockerfile.armhf -t tkurki/signalk-server:linux-armhf-"$BRANCH" .'
