language: node_js
node_js:
  - "lts/*"

sudo: required

services:
  - docker

stages:
  - mocha
  - test
  - multiarch

env:
  - ARCH=amd64
  - ARCH=armhf


jobs:
  include:
    - stage: mocha
      script:
        - echo "mocha"
        # - npm test
    - stage: test
      script:
        - echo "building $ARCH"
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build -f "Dockerfile.$ARCH" -t tkurki/signalk-server:linux-"$ARCH"-"$BRANCH" .
    - stage: multiarch
      script:
        - echo multiarch
    #     - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    #     - ./make-manifest.sh
    #     - docker run --rm -v `pwd`:`pwd` -w `pwd` tkurki/manifest-tool --username="$DOCKER_USER" --password="$DOCKER_PASS" push from-spec docker-manifest.yml
